// View Page
const DASHBOARD = {
    REQUEST: 'DASHBOARD_REQUEST',
    SUCCESS: 'DASHBOARD_SUCCESS',
    FAILURE: 'DASHBOARD_FAILURE',
    GRAPH_SUCCESS: 'DASHBOARD_GRAPH_SUCCESS',
    GRAPH_FAILURE: 'DASHBOARD_GRAPH_FAILURE',
    NOTIFICATION: 'DASHBOARD_NOTIFICATION',
    ERRORSYSTEM: 'DASHBOARD_ERRORSYSTEM',
    ERRORSYSTEM_RESET: 'DASHBOARD_ERRORSYSTEM_RESET',
    LATEST_DATA_SUCCESS: 'LATEST_DATA_SUCCESS',
}
const USER = {
    // SEARCH: 'USERS_SEARCH',
    LIST_REQUEST: 'USERS_LIST_REQUEST',
    LIST_SUCCESS: 'USERS_LIST_SUCCESS',
    LIST_FAILURE: 'USERS_LIST_FAILURE',
    
    LATEST_DATA_SUCCESS: 'USER_LATEST_DATA_SUCCESS',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USERS_UPDATE_FAILURE',

    FIND_REQUEST: 'USERS_FIND_REQUEST',
    FIND_SUCCESS: 'USERS_FIND_SUCCESS',
    FIND_FAILURE: 'USERS_FIND_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',
    
    CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

    USERS_COUNT_CHANGE: 'USERS_COUNT_CHANGE',
    USERS_PAGE_CHANGE: 'USERS_PAGE_CHANGE',

    USERS_SEARCH: 'USERS_SEARCH'
}
const DEVICEDATA = {
    DATA: 'DATA',
    LATEST_READING: 'DEVICEDATA_LATEST_READING',
    LAST_READING: 'DEVICEDATA_LAST_READING',
    AVERAGE_READING: 'DEVICEDATA_AVERAGE_READING',
    AVERAGE_ERROR: 'DEVICEDATA_AVERAGE_ERROR',
    TOTAL_ERROR: 'DEVICEDATA_TOTAL_ERROR'
}
const SITE = {
    DATA: 'DATA',
    LATEST_READING: 'SITE_LATEST_READING',
    LAST_READING: 'SITE_LAST_READING',
    AVERAGE_READING: 'SITE_AVERAGE_READING',
    AVERAGE_ERROR: 'SITE_AVERAGE_ERROR',
    TOTAL_ERROR: 'SITE_TOTAL_ERROR',
    LATEST_DATA_SUCCESS: 'SITE_LATEST_DATA_SUCCESS',
}
const TOURING = {
    DATA: 'DATA',
    TOURING_SEARCH: 'DEVICEDATA_SEARCH',
    LOGS_COUNT_CHANGE: 'LOGS_COUNT_CHANGE',
    LOGS_PAGE_CHANGE: 'LOGS_PAGE_CHANGE',
    LATEST_DATA_SUCCESS: 'TOURING_LATEST_DATA_SUCCESS',
}
const DATAPLAN = {
    DATA: 'FENCE LIST',
    LATEST_READING: 'FENCEDATA_LATEST_READING',
    LAST_READING: 'FENCEDATA_LAST_READING',
    AVERAGE_READING: 'FENCEDATA_AVERAGE_READING',
    AVERAGE_ERROR: 'FENCEDATA_AVERAGE_ERROR',
    TOTAL_ERROR: 'FENCEDATA_TOTAL_ERROR',
    ALLDATABYID: 'ALLDATABYID'
}

// Others
const ROLE = {
    SUPER: 'super',
    ADMIN: 'admin',
    MANAGER: 'manager'
}

const PATH = {
    LOGIN: '/login'
}

export const CONSTANTS = {
    CLEAR: 'CLEAR',
    TIME_IDLE: 30, // value in minute

    DASHBOARD,
    USER,
    DEVICEDATA,
    SITE,
    DATAPLAN,
    TOURING,

    ROLE,
    PATH,
}